require: rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
  Exclude:
    - config/environments/*.rb

Rails/I18nLocaleTexts:
  Enabled: false